#!/usr/bin/env python3
"""Generate memory/INDEX.generated.md, the machine index of the memory layer.

Deterministic and idempotent: same sources produce identical bytes (the
header carries a hash of the sources, never a timestamp). MEMORY.md stays
the human dashboard; this file is the machine index, read on demand, never
auto-loaded, never edited by hand. On a git conflict, never merge this file
by hand: fix the sources and regenerate with --write. See docs/ADVANCED.md.
"""
import argparse, hashlib, os, re, sys

NON_NODES = {"MEMORY.md", "CLAUDE.md", "INDEX.generated.md"}
LINK_ROW = re.compile(r"^- \[[^\]]+\]\(([A-Za-z0-9_\-]+\.md)\)")
HEADER = ("<!-- GENERATED by scripts/build_index.py, DO NOT EDIT BY HAND. -->\n"
          "<!-- On a git conflict, never merge this file by hand: fix the "
          "sources and regenerate with `python3 scripts/build_index.py "
          "--write`. -->\n"
          "<!-- sources-hash: {h} -->\n")


def is_skipped(fn):
    """Files excluded from the index: non-nodes, templates, and examples."""
    return (fn in NON_NODES or fn.endswith("_template.md")
            or fn.endswith("_example.md"))


def split_frontmatter(text):
    if not text.startswith("---\n"):
        return {}, text
    end = text.find("\n---", 4)
    if end == -1:
        return {}, text
    fm = {}
    for line in text[4:end].splitlines():
        if ":" in line and not line.startswith((" ", "\t", "#")):
            k, v = line.split(":", 1)
            fm[k.strip()] = v.strip()
    return fm, text[end + 4:]


def sources(repo):
    """All files that determine the index, in stable order."""
    out = []
    mem = os.path.join(repo, "memory")
    for base in (mem, os.path.join(mem, "archive")):
        if os.path.isdir(base):
            for fn in sorted(os.listdir(base)):
                if fn.endswith(".md") and not is_skipped(fn):
                    out.append(os.path.join(base, fn))
    return out


def sources_hash(repo):
    h = hashlib.sha256()
    for p in sources(repo):
        h.update(os.path.relpath(p, repo).encode() + b"\0")
        with open(p, "rb") as fh:
            h.update(fh.read())
        h.update(b"\0")
    return h.hexdigest()[:16]


POINTER = re.compile(r"`([^`]+/)`")


def memory_index_meta(repo):
    """file.md -> (section of MEMORY.md, folder pointer from the line, if any)."""
    p = os.path.join(repo, "memory", "MEMORY.md")
    cats, ptrs = {}, {}
    if not os.path.isfile(p):
        return cats, ptrs
    section = None
    with open(p, encoding="utf-8") as fh:
        for line in fh:
            if line.startswith("## "):
                section = line[3:].strip()
            m = LINK_ROW.match(line.strip())
            if m and section:
                cats.setdefault(m.group(1), section)
                mp = POINTER.search(line)
                if mp:
                    ptrs.setdefault(m.group(1), mp.group(1))
    return cats, ptrs


def next_action(body):
    lines = body.splitlines()
    for i, ln in enumerate(lines):
        if ln.strip().lower() == "## next action":
            for cand in lines[i + 1:]:
                s = cand.strip()
                if s.startswith("## "):
                    break
                if s and not s.startswith("<!--") and not s.startswith("["):
                    return " ".join(s.split())[:90]
            break
    return "-"


def row(stem, fm, body, ptr=None):
    emoji = fm.get("status", "").strip()[:1] or "."
    nxt = next_action(body)
    dl = fm.get("deadline", "")
    dl = f" - deadline {dl}" if dl else ""
    tail = f" - `{ptr}`" if ptr else ""
    return f"- {emoji} `{stem}` - Next: {nxt}{dl}{tail}\n"


def render(repo):
    mem = os.path.join(repo, "memory")
    nodes = {}
    for fn in sorted(os.listdir(mem)):
        if not fn.endswith(".md") or is_skipped(fn):
            continue
        with open(os.path.join(mem, fn), encoding="utf-8") as fh:
            fm, body = split_frontmatter(fh.read())
        nodes[fn] = (fm, body)
    arch = os.path.join(mem, "archive")
    n_arch = len([f for f in os.listdir(arch) if f.endswith(".md")]) if os.path.isdir(arch) else 0
    cats, ptrs = memory_index_meta(repo)

    out = [HEADER.format(h=sources_hash(repo)), "\n# INDEX (generated)\n"]

    projects = {fn: v for fn, v in nodes.items() if v[0].get("type") == "project"}
    by_cat = {}
    for fn, v in projects.items():
        by_cat.setdefault(cats.get(fn, "(no line in MEMORY.md)"), {})[fn] = v
    for cat in sorted(by_cat):
        out.append(f"\n## {cat}\n")
        for fn in sorted(by_cat[cat]):
            fm, body = by_cat[cat][fn]
            out.append(row(fn[:-3], fm, body, ptrs.get(fn)))

    for title, typ in (("Strategic", "strategic"), ("References", "reference"),
                       ("Feedback", "feedback")):
        sel = {fn: v for fn, v in nodes.items() if v[0].get("type") == typ}
        if sel:
            out.append(f"\n## {title}\n")
            for fn in sorted(sel):
                fm, body = sel[fn]
                if typ == "strategic":
                    out.append(row(fn[:-3], fm, body, ptrs.get(fn)))
                else:
                    out.append(f"- `{fn[:-3]}` - {fm.get('description', '(no description)')}\n")

    out.append(f"\n## Archive\nArchive: {n_arch} files (memory/archive/)\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--repo", default=None)
    g = ap.add_mutually_exclusive_group()
    g.add_argument("--write", action="store_true")
    g.add_argument("--check", action="store_true")
    args = ap.parse_args()
    repo = args.repo
    if not repo:
        import subprocess
        repo = subprocess.run(["git", "rev-parse", "--show-toplevel"],
                              capture_output=True, text=True).stdout.strip()
    if not repo or not os.path.isdir(os.path.join(repo, "memory")):
        print("build_index: repo/memory not found (use --repo)", file=sys.stderr)
        sys.exit(2)
    text = render(repo)
    target = os.path.join(repo, "memory", "INDEX.generated.md")
    if args.write:
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"written: {target}")
    elif args.check:
        current = open(target, encoding="utf-8").read() if os.path.isfile(target) else ""
        sys.exit(0 if current == text else 1)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
